config/routes.rb
Rails.application.routes.draw do
  get 'reports/new'

  get 'reports/edit'

  get 'reports/show'

  get 'welcome/index'

  get 'stores/search'

  get '/stores/:id', to: 'stores#show', as: 'store'

  resources :reports

  root 'welcome#index'

end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :food_category
  belongs_to :unit, :foreign_key => "desired_unit_id"
end

app/models/food_availability.rb
class FoodAvailability < ActiveRecord::Base
  belongs_to :report
  belongs_to :food
  belongs_to :unit, :foreign_key => "actual_unit_id"

  validates :price, presence: true, unless: ->(availability){availability.unavailable.present?}
  validates :unavailable, presence: true, unless: ->(availability){availability.price.present? || availability.sale.present?}

end

app/models/food_category.rb
class FoodCategory < ActiveRecord::Base
  has_many :food
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :store
  belongs_to :store_type

  has_many :food_availabilities
  accepts_nested_attributes_for :food_availabilities

  validates :store_type_id, :presence => true
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :reports

  def self.search query
    where('name ILIKE ?', "%#{query}%")
  end
end

app/models/store_type.rb
class StoreType < ActiveRecord::Base
end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def new
    @report = Report.new
    Food.all.each do |food|
      @report.food_availabilities.build(:food_id => food.id,
                                        :quantity => food.desired_quantity,
                                        :actual_unit_id => food.desired_unit_id)
    end

    @store = Store.find params[:store_id]
    @food_categories = FoodCategory.includes(food: [:unit])
  end

  def create
    params.permit!
    @report = Report.new(params[:report])
    if @report.save
      redirect_to @report
    else
      puts @report.errors.inspect
      puts @report.inspect
      Food.all.each do |food|
        @report.food_availabilities.build(:food_id => food.id,
                                          :quantity => food.desired_quantity,
                                          :actual_unit_id => food.desired_unit_id)
      end
      @store = Store.find @report[:store_id]
      @food_categories = FoodCategory.includes(food: [:unit])
      render action: :new
    end
  end

  def edit
  end

  def show
    @report = Report.find params[:id]
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def search
    @stores = Store.search params[:q]
  end
  def show
    @store = Store.includes(:reports).find params[:id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="footer-content">

  <div class="footer-section col-sm-4">
    <h5>Bugs and Feature Requests</h5>
    <a href="https://github.com/JHKennedy4/food_mapper/issues" class="btn btn-lg btn-default">Issue Tracker</a>
  </div>

  <div class="footer-section col-sm-4">
    <h5>Source and Citations</h5>
    <a href="https://github.com/jhkennedy4/food_mapper" class="btn btn-lg btn-default">View on GitHub</a>
  </div>

  <div class="footer-section col-sm-4">
    <h5>Contact</h5>
    <%= mail_to "me@projectfooddesert.org" do %>
      <div class="btn btn-lg btn-default">me@projectfooddesert.org</div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Food Desert</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta property="og:title" content="Project Food Desert" />
  <meta property="og:url" content="http://www.projectfooddesert.org/" />
  <meta property="og:image" content="http://www.projectfooddesert.org<%= image_path 'og_image.png' %>" />
  <meta property="og:description" content="Tools for researchers examining food availability in the United States" />
</head>
<body>

  <div id="wrapper">

    <div id="search" class="bg-primary">
      <div class="container">
        <a href="/">
          <%= image_tag 'carrot-lg.png', height: '22', class: "logo" %>
          <%= image_tag 'logo.png', height: "22" %>
        </a>
        <%= render :partial => 'stores/search_input' %>
      </div>
    </div>


    <!-- page content -->
    <div id="content" class="container">
      <%= yield %>
    </div>
    <!-- page content -->


    <div id="footer" class="bg-primary">
      <div class="container">
        <%= render :partial => 'layouts/footer' %>
      </div>
    </div>

  </div>

</body>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>

app/views/reports/edit.html.erb
<h1>Reports#edit</h1>
<p>Find me in app/views/reports/edit.html.erb</p>

app/views/reports/new.html.erb
<div class="center">
  <h4>
    USDA Community Food Security Assessment Toolkit
  </h4>
  <h1>
    Food Store Survey Instrument
  </h1>
  <div class="highlight">
    <h4>
      <%= link_to @store.name, store_path(@store) %>
    </h4>
    <div>
      <%= @store.address1 %>
    </div>
    <div>
      <%= @store.address2 %>
    </div>
    <div>
      <%= @store.city %>, <%= @store.state %> <%= @store.zip_code %>
    </div>
  </div>
</div>

<% if @report.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

    <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @report, url: reports_path do |f| %>
  <%= f.collection_select(:store_type_id, StoreType.all, :id, :store_type, {prompt: "Select Store Type"},{:class => "form-control input-lg"}) %>


  <h3>Read the following to the store manager before conducting the store survey:</h3>
  <div>
    <p>
      Thank you for allowing me to spend some time in your store collecting information on the availability of selected food items and their prices.
    </p>
    <p>
      The information that we are collecting from a wide variety of stores in the area will help create a profile of food availability and costs in the community.
    </p>
  </div>
  <h3>To the Data Collector:</h3>
  <div>
    <p>
      Please complete the following table by walking through the store and recording the price and weight or volume of the least expensive item for each food listed.
    </p>
    <p>
      The table includes the unit of measure that should be selected for each food. For example potatoes are measured in pounds, eggs are measured by the dozen.
    </p>
    <p>
      It is important that the prices recorded are for the specific food item in the table with no substitutions. If a food item is unavailable on the day that you visit the store, but is usually in stock check with the manager for the normal price.
    </p>
    <p>
      If a food is never in stock mark the the box labeled <b>unavailable</b>. If a food is on sale, check the box marked <b>sale</b> next to the price.
    </p>
  </div>


  <%= f.hidden_field :store_id, :value => @store.id %>


  <% category = nil %>
  <%= f.fields_for :food_availabilities, @report.food_availabilities do |ff| %>

    <% food = Food.find(ff.object.food_id) %>
    <% if (category == nil || category.id != food.food_category_id ) %>
      <% category = FoodCategory.find(food.food_category_id) %>
      <h3><%= category.category %></h3>
    <% end %>
    <h4><%= food.food %></h4>

    <%= ff.hidden_field :food_id, :value => ff.object.food_id %>

    <div class="form-group">
      <%= ff.check_box :unavailable  %>
      <%= ff.label :unavailable %>
    </div>

    <div class="form-group">
      <%= ff.label :price, "Lowest Price" %>
      <div class="input-group">
      <div class="input-group-addon">$</div>
      <%= ff.text_field :price, class: "form-control input-lg" %>
      </div>
    </div>
    <div class="form-group">
      <%= ff.check_box :sale %>
      <%= ff.label :sale %>
    </div>

    <div class="form-group">
      <%= ff.label :quantity %>
      <%= ff.text_field :quantity, class: "form-control input-lg" %>
    </div>

    <div class="form-group">
      <%= ff.label :actual_unit_id, "Unit" %>
      <%= ff.collection_select(:actual_unit_id, Unit.all, :id, :unit, {},{:class => "form-control input-lg"}) %>
    </div>
  <% end %>


  <%= f.submit :Submit, class: "form-control btn-primary btn-lg input-lg" %>
<% end %>

app/views/reports/show.html.erb
<div class="center">
<h1>Food Availability Report</h1>
<div class="highlight">
  <h4>
    <%= link_to @report.store.name, store_path(@report.store)%>
  </h4>
  <div>
    <%= @report.store.address1 %>
  </div>
  <div>
    <%= @report.store.address2 %>
  </div>
  <div>
    <%= @report.store.city %>, <%= @report.store.state %> <%= @report.store.zip_code %>
  </div>
</div>
</div>

<div>Submitted: <%= @report.created_at %></div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Food Type</th>
      <th>Cost</th>
      <th>per Quantity</th>
      <th>Unit</th>
      <th>Sale?</th>
    </tr>
  </thead>
  <tbody>

  <% category = nil %>

  <% @report.food_availabilities.each do |avail| %>

    <% if (category == nil || category.id != avail.food.food_category_id ) %>

      <% category = FoodCategory.find(avail.food.food_category_id) %>

      <tr><td colspan='5'><b><%= category.category %></b></td></tr>

    <% end %>

    <tr>
      <td>
        <%= avail.food.food %>
      </td>
      <% if avail.unavailable %>
        <td colspan='4'><b>Unavailable</b></td>
      <% else %>
      <td>
        <%= avail.price %>
      </td>
      <td>
        <%= avail.quantity %>
      </td>
      <td>
        <%= avail.unit.unit %>
      </td>
      <td>
        <%= avail.sale %>
      </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/stores/_search_input.html.erb
<%= form_tag({controller: 'stores', action: 'search'}, method: 'get', :class => 'form-inline'  ) do %>
  <div class="col-xs-8">
  <%= text_field_tag :q, params[:q], :id => 'search_field', :class => 'input-lg', :placeholder => 'Enter Store Name' %>
  </div>
  <div class="col-xs-4">
  <%= submit_tag "Search", :class => "btn btn-default btn-lg" %>
  </div>
<% end %>

app/views/stores/_search_results.html.erb
<ul class="list-unstyled">
<% @stores.each do |store| %>
  <li class="store">
    <h4 class=store-link">
      <%= link_to store.name, store %>
    </h4>
    <div>
      <%= store.address1 %>
    </div>
    <div>
      <%= store.address2 %>
    </div>
    <div>
      <%= store.city %>, <%= store.state %> <%= store.zip_code %>
    </div>
  </li>
<% end %>
</ul>

app/views/stores/search.html.erb
<div id="results">
<%= render :partial => 'stores/search_results' %>
</div>

app/views/stores/show.html.erb
<h1><%= @store.name %></h1>
<h2>
  <%= link_to "Create New Report", new_report_path(store_id: @store.id) %>
</h2>
<% if @store.reports.count > 0 %>
<h4>Previously Submitted:</h4>
<% else %>
  <h4>Be the first to submit a report for this store</h4>
<% end %>
<ul>
  <% @store.reports.each do |report| %>
    <li>
      <%= link_to report.created_at, report_path(report) %>
    </li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<br>
<p><b>Project Food Desert</b> exists to help researchers collect and analyze data on food availability in American cities.</p>
<p>Use the search bar to look up SNAP retailers from the <a href="http://www.fns.usda.gov/snap/retailerlocator">SNAP Retailer Locator</a></p>
<p>Then, submit the <b>USDA Food Security Assessment Toolkit</b> survey. The survey is based on the original USDA Food Security Assessment Toolkit found in Appendix C of <a href="http://scholarcommons.usf.edu/cgi/viewcontent.cgi?article=6003&context=etd">Desert in the Springs: Ethnography of a Food Desert [pdf]</a></p>
<p>This is an <i>alpha</i> stage application. Currently, the best way to get the data collected is to email <a href="mailto:me@projectfooddesert.org">me@projectfooddesert.org</a>, but tools for obtaining the data directly are coming shortly.</p>
<p>I welcome feature requests and bug reports by email, or by creating an issue on our <a href="https://github.com/jhkennedy4/food_mapper">GitHub page</a></p>
<p>At this stage in development, I expect issues to arrise, so please feel free to reach out to me preemptively to ensure that you don't run into any difficulties while collecting data</p>
<br>
<h5>Sincerely,</h5>
<h4>John Kennedy</h4>